apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ondam-ingress
  namespace: ondam
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # "/api/xxx" 를 "/xxx"로 바꿔서 백엔드로 전달
spec:
  rules:
    - host: ondam.localhost # 이 부분은 로컬 환경에서 'ondam.localhost'로 설정합니다.
      http:
        paths:
          - path: /api/(.*) # /api/로 시작하는 요청을 백엔드 서비스로 전달
            pathType: Prefix
            backend:
              service:
                name: ondam-backend-service # 백엔드 서비스 이름
                port:
                  number: 8080
          - path: / # 모든 다른 요청은 프론트엔드 서비스로 전달
            pathType: Prefix
            backend:
              service:
                name: ondam-frontend-service # 프론트엔드 서비스 이름
                port:
                  number: 80
