# apiVersion: networking.k8s.io/v1 # Ingress 리소스의 API 버전
# kind: Ingress # 리소스 종류: Ingress (HTTP 트래픽 라우팅)
# metadata:
#   name: ondam-ingress # Ingress 리소스의 이름
#   namespace: ondam # 배포 대상 네임스페이스
#   annotations:
#     # 기본적으로 NGINX Ingress 컨트롤러는 모든 HTTP 트래픽을 HTTPS로 리다이렉트한다.
#     # 이 설정을 "false"로 지정하면 HTTP 요청을 HTTPS로 자동 리다이렉트 하지 않는다.
#     # 개발 환경이나 SSL/TLS가 필요 없는 상황에서 유용하다.
#     nginx.ingress.kubernetes.io/ssl-redirect: "false"

# spec:
#   # 사용할 Ingress 컨트롤러의 클래스를 지정. 여기서는 NGINX Ingress 컨트롤러를 사용하도록 설정
#   ingressClassName: nginx
#   rules:
#     - host: ondam.localhost # 요청 도메인: 로컬 테스트용 도메인 (hosts 파일에 등록 필요)
#       http:
#         paths:
#           - path: /api # "/api"로 시작하는 모든 요청 처리
#             pathType: Prefix # 접두사 기준 매칭 (예: /api/v1 등도 포함)
#             backend:
#               service:
#                 name: ondam-back-ser # 요청을 전달할 백엔드 Service 이름
#                 port:
#                   number: 8080 # 백엔드 Service가 노출하는 포트 번호
#           - path: / # 그 외 모든 요청 처리 (정적 리소스 포함)
#             pathType: Prefix # 접두사 기준 매칭 (예: /main, /about 등)
#             backend:
#               service:
#                 name: ondam-front-ser # 요청을 전달할 프론트엔드 Service 이름
#                 port:
#                   number: 80 # 프론트엔드 Service가 노출하는 포트 번호

#################### ngrok 대응용

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ondam-ingress
  namespace: ondam
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ondam-back-ser
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ondam-front-ser
                port:
                  number: 80
