apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ondam-back-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Pive-Guyz/be14-4th-piveguyz-ondam.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ondam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
